# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZYAPPFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZYAPPFramework
  pod 'AFNetworking'
  pod 'SDWebImage', '~> 4.2.2'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'IQKeyboardManager','~> 4.0.13’
  pod 'FMDB'
  pod 'YYCategories', '~> 1.0.4'
  pod 'MJRefresh'
  pod 'MJExtension'
  
  target 'ZYAPPFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZYAPPFrameworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
